# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('datehired', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('wisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iwish', to='first_app.User')),
                ('wishes', models.ManyToManyField(related_name='youwish', to='first_app.User')),
            ],
        ),
    ]
